apiVersion: apps/v1
kind: Deployment

metadata: 
  name: journey-deployment
  labels:
    app: journey

spec:
  replicas: 5
  selector: 
    matchLabels: 
      app: journey
  template:
    spec:
      containers:
        - name: api-journey
          image: julioceno/nlw-journey-api:lasted # TODO: alterar a tag lasted
          resources:
            requests: 
              cpu: 200m
              memory: 256Mi
            limits: 
              cpu: 300m
              memory: 256Mi